In [55]:
import numpy as np
import gym 
import random
import time
from IPython.display import clear_output

In [56]:
env = gym.make("FrozenLake-v1")

/home/eyepatch/anaconda3/lib/python3.9/site-packages/gym/core.py:329: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/home/eyepatch/anaconda3/lib/python3.9/site-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [57]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size , action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [62]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [63]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        exploration_rate_treshold = random.uniform(0 , 1)
        if exploration_rate_treshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else :
            action = env.action_space.sample()
            
        new_state, reward , done , info = env.step(action)
        
        q_table[state , action] = q_table[state , action] * (1-learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        state = new_state
        rewards_current_episode +=reward
        
        if done == True:
            break
            
    exploration_decay_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    rewards_all_episodes.append(rewards_current_episode)

count = 1000
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
print("*******Average reward per thousand episodes ********")
for r in rewards_per_thousand_episodes:
    print(count," : ",str(sum(r/1000)))
    count += 1000
    
print("\n\n\n****Q-Table*****\n\n")
print(q_table)

*******Average reward per thousand episodes ********
1000  :  0.017000000000000008
2000  :  0.014000000000000005
3000  :  0.013000000000000005
4000  :  0.009000000000000001
5000  :  0.010000000000000002
6000  :  0.011000000000000003
7000  :  0.016000000000000007
8000  :  0.014000000000000005
9000  :  0.011000000000000003
10000  :  0.014000000000000005



****Q-Table*****


[[0.54660583 0.53956543 0.53902982 0.53052927]
 [0.28737335 0.41219095 0.36235056 0.51753942]
 [0.50636202 0.48326803 0.46621018 0.49283669]
 [0.34454566 0.23954731 0.2662215  0.4775415 ]
 [0.55532419 0.44867997 0.37562875 0.33776408]
 [0.         0.         0.         0.        ]
 [0.43122515 0.21484783 0.4332829  0.06666831]
 [0.         0.         0.         0.        ]
 [0.30265228 0.33018836 0.41481791 0.59715197]
 [0.46095073 0.64300085 0.45041933 0.39460273]
 [0.62956835 0.43795606 0.48291085 0.2898192 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.49131352 